#!/usr/bin/env python
import sys
from Bio import SeqIO, SeqFeature
import csv
import glob
import os
#combine gbk file in working dir
for f in glob.glob("*.gb"):
         os.system("cat "+f+" >> OutFile.gb")

# Parse combined records
combined_files = SeqIO.parse("OutFile.gb", format="genbank")

with open('gggenes-input.txt', mode='w') as parsed_output:   #write table for Suppl.data with hitsID, scores and lenght
                parsed_output = csv.writer(parsed_output, delimiter='\t', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                parsed_output.writerow(['gene', 'molecule', 'start', 'end', 'strand','locus_tag'])
# Print the info of each record
for rec in combined_files:
    contig=rec.id
    for feature in rec.features:
        if feature.type == 'gene':
            try:
                print(feature.qualifiers['gene'][0],"\t",contig,"\t",feature.location.start,"\t",feature.location.end,"\t",feature.location.strand,"\t",feature.qualifiers['locus_tag'][0],"\n", file=open('gggenes-input.txt', 'a'))
            except KeyError:
                print("Uknown","\t",contig,"\t",feature.location.start,"\t",feature.location.end,"\t",feature.location.strand,"\t",feature.qualifiers['locus_tag'][0],"\n",file=open('gggenes-input.txt', 'a'))
                
#removing combined file                
os.system("rm OutFile.gb") 
            
print('Done')
